
package org.webservice.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Emprunt", targetNamespace = "http://services.webservice.org/", wsdlLocation = "http://vij-pc:8080/webservice2396852418528692936/Emprunt?wsdl")
public class Emprunt_Service
    extends Service
{

    private final static URL EMPRUNT_WSDL_LOCATION;
    private final static WebServiceException EMPRUNT_EXCEPTION;
    private final static QName EMPRUNT_QNAME = new QName("http://services.webservice.org/", "Emprunt");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://vij-pc:8080/webservice2396852418528692936/Emprunt?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPRUNT_WSDL_LOCATION = url;
        EMPRUNT_EXCEPTION = e;
    }

    public Emprunt_Service() {
        super(__getWsdlLocation(), EMPRUNT_QNAME);
    }

    public Emprunt_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPRUNT_QNAME, features);
    }

    public Emprunt_Service(URL wsdlLocation) {
        super(wsdlLocation, EMPRUNT_QNAME);
    }

    public Emprunt_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPRUNT_QNAME, features);
    }

    public Emprunt_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Emprunt_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpruntWebservice
     */
    @WebEndpoint(name = "EmpruntWebservicePort")
    public EmpruntWebservice getEmpruntWebservicePort() {
        return super.getPort(new QName("http://services.webservice.org/", "EmpruntWebservicePort"), EmpruntWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpruntWebservice
     */
    @WebEndpoint(name = "EmpruntWebservicePort")
    public EmpruntWebservice getEmpruntWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.webservice.org/", "EmpruntWebservicePort"), EmpruntWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPRUNT_EXCEPTION!= null) {
            throw EMPRUNT_EXCEPTION;
        }
        return EMPRUNT_WSDL_LOCATION;
    }

}
