
package org.webservice.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationWebService", targetNamespace = "http://services.webservice.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationWebService {


    /**
     * 
     * @return
     *     returns java.util.List<org.webservice.services.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListeReservations", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.GetListeReservations")
    @ResponseWrapper(localName = "getListeReservationsResponse", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.GetListeReservationsResponse")
    @Action(input = "http://services.webservice.org/ReservationWebService/getListeReservationsRequest", output = "http://services.webservice.org/ReservationWebService/getListeReservationsResponse")
    public List<Reservation> getListeReservations();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerReservation", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.SupprimerReservation")
    @ResponseWrapper(localName = "supprimerReservationResponse", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.SupprimerReservationResponse")
    @Action(input = "http://services.webservice.org/ReservationWebService/supprimerReservationRequest", output = "http://services.webservice.org/ReservationWebService/supprimerReservationResponse")
    public void supprimerReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        Reservation arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "creerReservation", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.CreerReservation")
    @ResponseWrapper(localName = "creerReservationResponse", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.CreerReservationResponse")
    @Action(input = "http://services.webservice.org/ReservationWebService/creerReservationRequest", output = "http://services.webservice.org/ReservationWebService/creerReservationResponse")
    public void creerReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        Reservation arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.webservice.services.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListeReservationsByBookId", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.GetListeReservationsByBookId")
    @ResponseWrapper(localName = "getListeReservationsByBookIdResponse", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.GetListeReservationsByBookIdResponse")
    @Action(input = "http://services.webservice.org/ReservationWebService/getListeReservationsByBookIdRequest", output = "http://services.webservice.org/ReservationWebService/getListeReservationsByBookIdResponse")
    public List<Reservation> getListeReservationsByBookId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.webservice.services.Reservation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPremiereReservationDuLivreById", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.GetPremiereReservationDuLivreById")
    @ResponseWrapper(localName = "getPremiereReservationDuLivreByIdResponse", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.GetPremiereReservationDuLivreByIdResponse")
    @Action(input = "http://services.webservice.org/ReservationWebService/getPremiereReservationDuLivreByIdRequest", output = "http://services.webservice.org/ReservationWebService/getPremiereReservationDuLivreByIdResponse")
    public Reservation getPremiereReservationDuLivreById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
