
package org.webservice.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationWebService", targetNamespace = "http://services.webservice.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationWebService {


    /**
     * 
     * @return
     *     returns java.util.List<org.webservice.services.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListeReservation", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.GetListeReservation")
    @ResponseWrapper(localName = "getListeReservationResponse", targetNamespace = "http://services.webservice.org/", className = "org.webservice.services.GetListeReservationResponse")
    @Action(input = "http://services.webservice.org/ReservationWebService/getListeReservationRequest", output = "http://services.webservice.org/ReservationWebService/getListeReservationResponse")
    public List<Reservation> getListeReservation();

}
